openapi: 3.0.3
info:
  title: Turing Batch Experiment API
  version: 0.0.1
servers:
  - url: localhost:8080/v1
paths:
  "/projects":
    $ref: "projects.yaml#/paths/~1projects"
  "/projects/{project_id}/ensemblers":
    $ref: "ensemblers.yaml#/paths/~1projects~1{project_id}~1ensemblers"
  "/projects/{project_id}/ensemblers/{ensembler_id}":
    $ref: "ensemblers.yaml#/paths/~1projects~1{project_id}~1ensemblers~1{ensembler_id}"

  "/projects/{project_id}/jobs":
    get:
      summary: Returns a list of Ensembling jobs
      parameters:
        - in: path
          name: project_id
          schema:
            $ref: "#/components/schemas/Id"
          required: true
      responses:
        "200":
          description: TBU
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EnsemblingJob"

components:
  schemas:
    Id:
      type: "integer"
      format: "int32"

    EnsemblingJob:
      description: A JSON object that represents an ensembling job for batch experiment use cases
      properties:
        id:
          $ref: "#/components/schemas/Id"
        project_id:
          $ref: "#/components/schemas/Id"

    EnsemblingJobMeta:
      description: Ensembling job Metadata
      properties:
        name:
          type: "string"
        annotations:
          type: "object"
          additionalProperties:
            type: "string"

    EnsemblingJobSpec:
      description: Ensembling job Specification
      properties:
        source:
          $ref: "#/components/schemas/EnsemblingJobSource"
        predictions:
          type: "array"
          items:
            $ref: "#/components/schemas/EnsemblingJobPredictionSource"
        ensembler:
          $ref: "#/components/schemas/EnsemblingJobEnsemblerSpec"

    EnsemblingJobSource:
      type: "object"
      properties:
        dataset:
          $ref: "#/components/schemas/Dataset"
        join_on:
          type: "array"
          items:
            type: "string"

    Dataset:
      type: "object"
      required:
        - "type"
      properties:
        type:
          $ref: "#/components/schemas/DatasetType"
      discriminator:
        propertyName: "type"

    DatasetType:
      type: "string"
      enum:
        - "BQ"

    BigQueryDataset:
      allOf:
        - $ref: "#/components/schemas/Dataset"
        - type: object
          properties:
            bq_config:
              $ref: "#/components/schemas/BigQueryDatasetConfig"

    BigQueryDatasetConfig:
      properties:
        table:
          type: "string"
          pattern: '^[a-z][a-z0-9-]+\.\w+([_]?\w)+\.\w+([_]?\w)+$'
        features:
          type: "array"
          items:
            type: "string"
        query:
          type: "string"
        options:
          type: "object"
          additionalProperties:
            type: "string"

    EnsemblingJobPredictionSource:
      type: "object"
      allOf:
        - $ref: "#/components/schemas/EnsemblingJobSource"
        - type: "object"
          properties:
            columns:
              type: "array"
              items:
                type: "string"

    EnsemblingJobEnsemblerSpec:
      type: "object"
      properties:
        uri:
          type: "string"
          format: "uri"
        result:
          type: "object"
          properties:
            type:
              $ref: "#/components/schemas/EnsemblingJobResultType"
            item_type:
              $ref: "#/components/schemas/EnsemblingJobResultType"
            column_name:
              type: "string"

    EnsemblingJobResultType:
      type: "string"
      enum:
        - DOUBLE
        - FLOAT
        - INTEGER
        - LONG
        - STRING
        - ARRAY

    PaginatedResults:
      type: "object"
      properties:
        paging:
          type: "object"
          properties:
            total:
              type: "integer"
              format: "int32"
              description: "Total number of results matching the query criteria"
            page:
              type: "integer"
              format: "int32"
              description: "Number of the current page"
            pages:
              type: "integer"
              format: "int32"
              description: "Total number of pages"

